### Create a new Container
POST http://localhost:3000/api/containers
Content-Type: application/json

{
  "containerCode": "FSCU5726799",
  "description": "FSCU5726799 x 40-ft non-operating reefer container"
}

### Get all Containers
GET http://localhost:3000/api/containers

### Get a Container by ID
GET http://localhost:3000/api/containers/1

### Update a Container by ID
PUT http://localhost:3000/api/containers/1
Content-Type: application/json

{
  "containerCode": "C654321",
  "description": "Updated container description"
}

### Delete a Container by ID
DELETE http://localhost:3000/api/containers/1
