### Create a new Image Pathimg
POST http://localhost:3000/api/images-pathimgs
Content-Type: application/json

{
  "path": "/path/to/image1.jpg",
  "description": "Description for the first image"
}

### Get all Images Pathimg
GET http://localhost:3000/api/images-pathimgs
Accept: application/json

###

### Get a specific Image Pathimg by ID
GET http://localhost:3000/api/images-pathimgs/1
Accept: application/json

###

### Update an existing Image Pathimg
PUT http://localhost:3000/api/images-pathimgs/1
Content-Type: application/json

{
  "pathimg": "/updated/path/to/image1.jpg",
  "description": "Updated description for the first image"
}

###

### Delete an Image Pathimg by ID
DELETE http://localhost:3000/api/images-pathimgs/1
Accept: application/json
