### Create a new Images Group
POST http://localhost:3000/api/images-groups
Content-Type: application/json

{
  "title": "New Group Title",
  "description": "Description of the group",
  "imagesPathimg": [{"id": 1}, {"id": 2}]
}

###

### Get all Images Groups
GET http://localhost:3000/api/images-groups
Accept: application/json

###

### Get a specific Images Group by ID
GET http://localhost:3000/api/images-groups/1
Accept: application/json

###

### Update an existing Images Group
PUT http://localhost:3000/api/images-groups/1
Content-Type: application/json

{
  "title": "Updated Group Title",
  "description": "Updated description of the group",
  "imagesPathimg": [2, 3, 4]  
}

###

### Delete an Images Group by ID
DELETE http://localhost:3000/api/images-groups/1
Accept: application/json
