### Create a new UnstuffingContainer entry
POST http://localhost:3000/api/unstuffing-containers
Content-Type: application/json

{
  "description": {
    "id": 1
  },
  "detailsShipment": {
    "id": 1
  }
}

### Get all UnstuffingContainer entries
GET http://localhost:3000/api/unstuffing-containers

### Get an UnstuffingContainer entry by ID
GET http://localhost:3000/api/unstuffing-containers/1

### Update an UnstuffingContainer entry by ID
PUT http://localhost:3000/api/unstuffing-containers/1
Content-Type: application/json

{
  "description": {
    "id": 2
  },
  "detailsShipment": {
    "id": 2
  }
}

### Delete an UnstuffingContainer entry by ID
DELETE http://localhost:3000/api/unstuffing-containers/1
