
###
GET http://localhost:3000/api/report/mbl_code/1

###
GET http://localhost:3000/api/report/mbl_code

###
GET http://localhost:3000/api/report

###
GET http://localhost:3000/api/report/ONEYHAME90065701

###
PATCH http://localhost:3000/api/report/1
Content-Type: application/json

{
  "code": "code001"
}

###
DELETE http://localhost:3000/api/report/ONEYHAME90065701
