### Obtener todos los Reports
GET http://localhost:3000/api/report
Content-Type: application/json

###

### Obtener un Report específico (reemplaza :id con el ID)
GET http://localhost:3000/api/report/:id
Content-Type: application/json

###

### Actualizar un Report (reemplaza :id con el ID)
PATCH http://localhost:3000/api/report/:id
Content-Type: application/json

{
  "t0_header": {
    "header_name": "Actualizado - FLAVIO A. PREZIOSA",
    "header_address": "Nueva dirección, Buenos Aires, Argentina"
  },
  "t1_details_shipment": {
    "vessel": "Actualizado - XIN CHANG SHA"
  }
}

###

### Eliminar un Report (reemplaza :id con el ID)
DELETE http://localhost:3000/api/report/:id
Content-Type: application/json
